name: GitHub Pages

on:
  push:
    branches:
      - main  # Gantilah dengan nama branch yang digunakan untuk development kamu, jika bukan `main`

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.7  # Sesuaikan dengan versi Ruby yang kamu gunakan

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build Jekyll site
      run: |
        bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # Token otomatis GitHub untuk akses
        publish_dir: ./_site  # Direktori tempat output build Jekyll disimpan
        user_name: 'Your GitHub Username'  # Ganti dengan nama pengguna GitHub kamu
        user_email: 'Your GitHub Email'  # Ganti dengan email GitHub kamu
